name: uniflutterloginscreens
description: "A new project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  auth_buttons: 3.0.3
  firebase_core: any
  firebase_auth: ^5.5.0
  cloud_firestore: any
  google_sign_in: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
