// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxnQ1wjRAx8VVSyo9vqcOYlS9niy575PA',
    appId: '1:1073239252002:web:ca683dce6e26cbb5283e7b',
    messagingSenderId: '1073239252002',
    projectId: 'uni-praactice',
    authDomain: 'uni-praactice.firebaseapp.com',
    storageBucket: 'uni-praactice.firebasestorage.app',
    measurementId: 'G-J5X0ZYGNNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKQRvn63YfM5v0wGE7lD-fSME3TEV8HwE',
    appId: '1:1073239252002:android:837f4c7c65457a79283e7b',
    messagingSenderId: '1073239252002',
    projectId: 'uni-praactice',
    storageBucket: 'uni-praactice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08feLJJun2ETAt-FauM8GPGilKWXc868',
    appId: '1:1073239252002:ios:b90715b037cd1d13283e7b',
    messagingSenderId: '1073239252002',
    projectId: 'uni-praactice',
    storageBucket: 'uni-praactice.firebasestorage.app',
    iosBundleId: 'com.example.uniflutterloginscreens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC08feLJJun2ETAt-FauM8GPGilKWXc868',
    appId: '1:1073239252002:ios:b90715b037cd1d13283e7b',
    messagingSenderId: '1073239252002',
    projectId: 'uni-praactice',
    storageBucket: 'uni-praactice.firebasestorage.app',
    iosBundleId: 'com.example.uniflutterloginscreens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxnQ1wjRAx8VVSyo9vqcOYlS9niy575PA',
    appId: '1:1073239252002:web:6525c996c12608b8283e7b',
    messagingSenderId: '1073239252002',
    projectId: 'uni-praactice',
    authDomain: 'uni-praactice.firebaseapp.com',
    storageBucket: 'uni-praactice.firebasestorage.app',
    measurementId: 'G-ZVRRYCEPYS',
  );
}
